title: Refuel Robotics
description: Software-first company building hardware integration and motion control systems for autonomous vehicle refueling
theme: minima
url: https://mnamburi9.github.io
baseurl: /robo-jerry
author:
  name: Refuel Robotics Team
github_username: mnamburi9 