title: Robo Jerry
description: Stealth robotics startup focused on advanced autonomous systems
theme: minima
url: "https://mnamburi9.github.io"
baseurl: "/robo-jerry"
author:
  name: Robo Jerry Team
  email: contact@robojerry.com
github_username: mnamburi9 